### ISSUE TITLE
unable to set vacuum job history limits to 0

### ISSUE THREAD

**Issue by krancour** [brigadecore/charts#60]
Setting `vacuum.successfulJobsHistoryLimit` to `0` upon install/upgrade has no effect, but setting it to any positive value has the intended effect.

These lines appear in the template for the vacuum CronJob:

```
spec:
  # ...
  successfulJobsHistoryLimit: {{ default 10 .Values.vacuum.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 10 .Values.vacuum.failedJobsHistoryLimit }}
```

Per sprig documentation, for numeric types, the `default` function considers `0` as unset-- hence, explicitly providing the value `0` results in getting the default-- `10`.

I propose adding defaults to `values.yaml` and removing use of the `default` function here.
